name: Update README with GITMCP

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 8 AM UTC
  workflow_dispatch:       # Allow manual triggering

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Generate repo list in README
        uses: 9Mirrors-Lab/readme-repos-list@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: user:9Mirrors-Lab in:name know fork:true
          path: README.md
          start: '<!-- REPO-LIST:START -->'
          end: '<!-- REPO-LIST:END -->'
          max: 100
