name: Update README with Knowledge Repos

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate repo list in README
        uses: DenverCoderOne/readme-repos-list@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: 9Mirrors-Lab
          prefix: 'know-'                   # filters repos by prefix
          max: 100                          # optional limit
          filename: README.md
          start: '<!-- REPO-LIST:START -->'
          end: '<!-- REPO-LIST:END -->'
          template: '- [{{name}}]({{url}})'  # renders clean markdown links
