name: Update README with Knowledge Repos

on:
  schedule:
    - cron: '0 8 * * *' # daily at 8AM UTC
  workflow_dispatch:

permissions:
  contents: write   # <-- This is the key fix

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Update README with list of repos
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: user:9Mirrors-Lab know- in:name
          path: README.md
          start: '<!-- REPO-LIST:START -->'
          end: '<!-- REPO-LIST:END -->'
          commit-message: 'chore: update repo list'
